<?php

namespace OC\GestionBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastArticle()
    {
       $query = $this->createQueryBuilder('a');
       
       $result = $query
       ->innerJoin('a.section','sec')
       ->addSelect('sec')
       ->innerJoin('a.imageAs','im')
       ->addSelect('im')
       ->orderBy('a.id','DESC')
       ->setMAxResults('1');
      return $result ->getQuery()
       ->getResult();
    }
}
