<?php

namespace OC\GestionBundle\Repository;

/**
 * ImageARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageARepository extends \Doctrine\ORM\EntityRepository
{
}
