<?php

namespace OC\GestionBundle\Repository;

/**
 * TextARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextARepository extends \Doctrine\ORM\EntityRepository
{
}
